name = "MaskPII"
uuid = "e51ab4cc-94ad-4aad-a579-d543f796cd4d"
version = "0.1.0"
authors = ["Finite Field, K.K."]
license = "MIT"
description = "A lightweight Julia library for masking PII such as emails and phone numbers."
homepage = "https://finitefield.org/en/oss/mask-pii"
repository = "https://github.com/finitefield-org/mask-pii"
issues = "https://github.com/finitefield-org/mask-pii/issues"
keywords = ["pii", "masking", "email", "phone", "privacy"]

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
